{% set name = "aiidalab" %}
{% set version = "24.9.0" %}
{% set sha256 = "06611f59b06716e598216b14a325542b2e6471230c520e2e512f0e1541e451d8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiidalab-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - aiidalab = aiidalab.__main__:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - cachetools >=4.1,=4
    - click >=7.0,<9
    - click-spinner >=0.1,=0
    - dulwich >=0.20,=0
    - packaging >=20.1,<22
    - pip
    - python >=3.8
    - requests >=2.27,=2
    - requests-cache >=1.0,=1
    - setuptools
    - tabulate >=0.8,=0
    - toml >=0.10,=0
    - traitlets >=5.0,=5
    - watchdog >=2.3,=2

test:
  imports:
    - aiidalab
  commands:
    - pip check
    - aiidalab --help
  requires:
    - pip

about:
  home: https://github.com/aiidalab/aiidalab
  summary: Implements core functions of AiiDAlab.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - csadorf
    - yakutovicha
    - unkcpz
    - danielhollas
