{% set name = "aiidalab" %}
{% set version = "22.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiidalab-{{ version }}.tar.gz
  sha256: 2fa145dd824e5a5817952dd6dec09d1965c40406a42417becefa7a757a7db8b2

build:
  entry_points:
    - aiidalab = aiidalab.__main__:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - aiida-core >=2.0.0,<3
    - cachecontrol >=0.12,=0
    - cachetools >=4.1,=4
    - click >=7.0,<9
    - click-spinner >=0.1,=0
    - dacite >=1.6,=1
    - dulwich >=0.20,=0
    - ipython >=7.0,=7
    - jinja2 >=2.11.3,<4
    - jsonref >=0.2,=0
    - jsonschema >=3.2,=3
    - markupsafe ==2.0.1
    - packaging >=20.1
    - python >=3.7
    - requests >=2.27,=2
    - requests-cache >=0.5,=0
    - requests-mock >=1.8,=1
    - ruamel.yaml >=0.16,=0
    - tabulate >=0.8,=0
    - toml >=0.10,=0
    - traitlets >=5.0,=5
    - urllib3 >=1.24,=1
    - watchdog >=0.10,=0

test:
  imports:
    - aiidalab
  commands:
    - pip check
    - aiidalab --help
  requires:
    - pip

about:
  home: https://github.com/aiidalab/aiidalab
  summary: Implements core functions of AiiDAlab.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - csadorf
    - yakutovicha
    - unkcpz
    - danielhollas
